spring.application.name=marketplace
spring.datasource.url=jdbc:postgresql://localhost:15432/marketplace
spring.datasource.username=marketplace
spring.datasource.password=marketplace

data.storage.location=F:/marketplace/data/media

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

app.phone.supported-regions=RU
app.jwt.secretKey=${MARKETPLACE_JWT_SECRET}
app.jwt.access-token-ttl=PT15M

app.initial-admin.name=${MARKETPLACE_ADMIN_NAME}
app.initial-admin.telephone=${MARKETPLACE_ADMIN_TELEPHONE}
app.initial-admin.password=${MARKETPLACE_ADMIN_PASSWORD}

logging.file.name=logs/marketplace.log