spring.application.name=marketplace
spring.datasource.url=jdbc:postgresql://localhost:15432/marketplace
spring.datasource.username=marketplace
spring.datasource.password=marketplace

data.storage.location=F:/marketplace/data/media

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
